export const projects = [
  {
    title: "APC Data Capture",
    group: "mobile",
    detailsPage: "/projects/mim",
    description: `
    This is a data capture application. 
    Used to store data of agents in all sectors for the APC Party.
    `,
    image: "/images/apc/apc.png",
    tags: ["Dart", "Flutter", "Firebase"],
    source: "#",
    visit: "#",
    githubLink: "",
    id: 1,
  },

  {
    title: "Bioplus",
    group: "mobile",
    detailsPage: "/projects/bioplus",
    description: "A mobile app for selling and buying otc pharmaceuticals ",
    image: "/images/project/bioplus.jpg",
    tags: ["Dart", "Flutter", "Firebase"],
    source: "#",
    visit: "#",
    githubLink: "",
    id: 4,
  },
  {
    title: "BTB",
    group: "mobile",
    detailsPage: "/projects/btb",
    description: "A Binance Cryptocurrency trading bot ",
    image: "/images/project/btb.jpg",
    tags: ["Dart", "Python"],
    source: "#",
    visit: "#",
    githubLink: "",
    id: 5,
  },
  {
    title: "Portfolio",
    group: "web",
    detailsPage: "/",
    description:
      "My personal website for detailed explanation of all my projects.",
    image: "/images/project/portfolio.jpg",
    tags: ["Next.js"],
    source: "/",
    visit: "/",
    githubLink: "",
    id: 6,
  },
  {
    title: "SmattLife",
    group: "web",
    detailsPage: "/projects/smattlife",
    description:
      "A website for selling health products, multivitiamins and other o.t.c drugs. Also offers health tips",
    image: "/images/project/smattlife.jpg",
    tags: ["Next.js"],
    source: "https://smattlife.com/",
    visit: "https://smattlife.com/",
    githubLink: "",
    id: 7,
  },
  {
    title: "Diary",
    group: "mobile",
    detailsPage: "/projects/diary",
    description:
      "An app to track daily activities and save notes for future use. Stores data on local memory.",
    image: "/images/project/smattlife.jpg",
    tags: ["Next.js"],
    source: "https://smattlife.com/",
    visit: "https://smattlife.com/",
    githubLink: "",
    id: 8,
  },
];
